import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';

const font = Plus_Jakarta_Sans({
  variable: '--font-jakarta-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Uploader',
  description: 'Generated by @anggifergian',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} antialiased`}>
        <div className="min-h-svh">
          <main className="mx-auto max-w-2xl lg:w-full">
            <div className="py-20 xl:py-40 px-4">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
